In [ ]:
from google.colab import files 


uploaded = files.upload()

Saving lv2.txt to lv2 (2).txt


In [ ]:
import numpy as np
file = open('lv2.txt','r')
line1 = file.readline()
line2 = file.readline()

vertext_count = int(line1) +1
x = int(line2)

In [ ]:
adj_matrix = np.zeros((vertext_count, vertext_count), dtype = 'int')
print(adj_matrix)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [ ]:
for i in range(x):
    line = file.readline()
    vertices = line.split() 
    u = int(vertices[0])
    v = int(vertices[1])
    adj_matrix[u][v] = 1
    adj_matrix[v][u] = 1
   
print(adj_matrix)
lina = int(file.readline())
nora = int(file.readline())
lara = int(file.readline())

[[0 1 1 1 0 0 0 0 0 0]
 [1 0 0 1 1 0 0 0 0 0]
 [1 0 0 1 0 0 0 0 0 0]
 [1 1 1 0 0 1 0 0 0 0]
 [0 1 0 0 0 0 0 1 1 0]
 [0 0 0 1 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 1 0 0]
 [0 0 0 0 1 0 1 0 1 0]
 [0 0 0 0 1 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [ ]:
color = np.empty(vertext_count, dtype = 'object')
color[:] ='WHITE'

In [ ]:
parent = np.empty(vertext_count, dtype = 'object')
parent[:] = np.NaN

In [ ]:
d= np.zeros(vertext_count,dtype = 'int')

In [ ]:
from queue import Queue
my_queue =  Queue(maxsize = vertext_count)

def bfs(g,s):
  color[s] = 'Gray'
  parent[s] = np.nan
  d[s] = 0
  my_queue.put(s)
  while not my_queue.empty():
    u = my_queue.get()
    for v in range (1,vertext_count):
      if adj_matrix[u][v] == 1:
        if color[v] == 'WHITE':
          color[v] = 'Gray'
          d[v] = d[u] + 1
          parent[v] = u
          my_queue.put(v)
    color[u] = 'BLACK'

    #print(str(u) + 'distance' + str(d[u])) 
  return d
  

In [ ]:
 distance = bfs(adj_matrix,1)
 
 n = bfs(adj_matrix, nora)[lina]
 l =bfs(adj_matrix,lara)[nora]

In [ ]:
if n>l:
  print('Nora')
else:
  print('Lara')
  


Nora
